soc: samsung: debug: Fix truncated snprintf
../../../../../../kernel/samsung/gta4xls/drivers/soc/samsung/debug/debug-snapshot-pmsg.c:76:16: error: 'snprintf' will always be truncated; specified size is 68, but format string expands to at least 69 [-Werror,
-Wfortify-source]
   76 |                 logbuf_len = snprintf(logbuf, LOGGER_HEADER_SIZE,
      |                              ^
1 error generated.

Change-Id: I222b7cad289f897218e4192b22554b10d031ccd2

arm64: Add 32-bit sigcontext definition to uapi signcontext.h

The arm64 uapi sigcontext.h can be included by 32-bit userspace
modules. Since arm and arm64 sigcontext definition are not
compatible, add arm sigcontext definition to arm64 sigcontext.h.

Change-Id: I94109b094f6c8376fdaeb2822d7b26d18ddfb2bc
Signed-off-by: Ameya Thakur <ameyat@codeaurora.org>
Signed-off-by: Venkata Narendra Kumar Gutta <vnkgutta@codeaurora.org>

arm64: Fix CONFIG_64BIT leak to userspace

Commit c7c0eecf894c3e353499fffd6f2ddaefc89bbd4a disabled the use of config
options in uapi headers. Use __aarch64__ which is a compiler-defined
method of obtaining the architecture instead of CONFIG_64BIT.

Fixes the following error:
    error: kernel/google/raviole/arch/arm64/include/uapi/asm/sigcontext.h:
        leak CONFIG_64BIT to user-space

Change-Id: Ie1f22679882acbc3e253316d5281287956a4febd

Revert "arm64: Add 32-bit sigcontext definition to uapi signcontext.h"